// =====================================================================
// FILE: MerkaiTrial.Application/DTOs/CustomFieldDtos.cs
//
// NEW FILE (075 — custom fields, Round A).
//
// THE WIRE FORMAT FOR A VALUE IS A STRING, IN ONE INVARIANT SHAPE PER
// TYPE, and that is deliberate:
//
//   text      as typed                      "Mumbai head office"
//   number    invariant, '.' decimal point  "1250.5"
//   date      ISO calendar date             "2027-03-01"
//   dropdown  the option's KEY              "o_3fa8b21c"
//   checkbox  "true" (unticked = empty)     "true"
//
// That is exactly what a browser posts from <input type="number">,
// <input type="date"> and a <select>, whatever language the browser is
// in, so the form can pass values straight through. Culture only enters
// at DISPLAY time, on the page, using the tenant's own number and date
// format. CustomFieldValueRules (Application/Configuration) is the one
// place that turns these strings into typed values and back.
//
// 076 — ShowInList on the definition DTOs, and CustomFieldFilter: one
// condition on one field, as the list page sends it to the API.
//
// 079 — MapToContactFieldId / MapToDealFieldId on the definition DTOs:
// on a Lead field, the Contact field and Deal field that receive its
// value when the lead is converted. Ignored (and stored as null) on any
// other kind of field. Saving a definition sends the WHOLE field, so a
// null here clears the mapping — the Settings page always sends both.
// =====================================================================

namespace MerkaiTrial.Application.DTOs
{
    /// <summary>One choice on a dropdown field.</summary>
    public class CustomFieldOptionDto
    {
        /// <summary>
        /// Stable id, generated by the server ("o_" + 8 hex). Empty on an
        /// option the person has just added; the server fills it in.
        /// Never shown, never changed, and the thing a value stores.
        /// </summary>
        public string Key { get; set; } = string.Empty;

        public string Label { get; set; } = string.Empty;

        /// <summary>
        /// False = retired. Not offered on forms any more; records that
        /// already picked it keep it and still display its label.
        /// </summary>
        public bool IsActive { get; set; } = true;
    }

    public class CustomFieldDefinitionDto
    {
        public Guid Id { get; set; }
        public string EntityType { get; set; } = string.Empty;
        public string Label { get; set; } = string.Empty;
        public string FieldType { get; set; } = string.Empty;
        public string? HelpText { get; set; }
        public bool IsRequired { get; set; }
        public bool IsActive { get; set; }
        public int SortOrder { get; set; }
        public int DecimalPlaces { get; set; }

        /// <summary>076. A column on the list page.</summary>
        public bool ShowInList { get; set; }

        /// <summary>079. Lead fields only: the Contact field that receives this value on conversion.</summary>
        public Guid? MapToContactFieldId { get; set; }

        /// <summary>079. Lead fields only: the Deal field that receives this value on conversion.</summary>
        public Guid? MapToDealFieldId { get; set; }

        public List<CustomFieldOptionDto> Options { get; set; } = new();

        /// <summary>
        /// How many live records (not soft-deleted) carry a value for this
        /// field. Drives the "used on 14 contacts" line and whether Delete
        /// is offered.
        /// </summary>
        public int ValueCount { get; set; }
    }

    /// <summary>
    /// Create and update share one shape. On UPDATE, EntityType and
    /// FieldType are ignored — a field's type is fixed once it exists,
    /// because changing "number" to "date" would orphan every value.
    /// </summary>
    public class SaveCustomFieldDefinitionDto
    {
        public string EntityType { get; set; } = string.Empty;
        public string Label { get; set; } = string.Empty;
        public string FieldType { get; set; } = string.Empty;
        public string? HelpText { get; set; }
        public bool IsRequired { get; set; }
        public bool IsActive { get; set; } = true;
        public int DecimalPlaces { get; set; }

        /// <summary>
        /// 076. A column on the list page. Refused past
        /// CustomFieldLimits.MaxListColumns active list columns.
        /// </summary>
        public bool ShowInList { get; set; }

        /// <summary>
        /// 079. Lead fields only. The Contact field (same type) that
        /// receives this value on conversion. Null = not copied. Refused
        /// if it is not a live Contact field of the same type, or if
        /// another Lead field already feeds it.
        /// </summary>
        public Guid? MapToContactFieldId { get; set; }

        /// <summary>079. Lead fields only. The Deal field that receives this value. Same rules.</summary>
        public Guid? MapToDealFieldId { get; set; }

        /// <summary>
        /// Dropdown only, and THE FULL LIST. An option that was there before
        /// and is missing now is removed — or, if any record uses it,
        /// retired instead, so nobody's saved value turns into "(unknown)".
        /// </summary>
        public List<CustomFieldOptionDto> Options { get; set; } = new();
    }

    /// <summary>
    /// 076. One condition on one custom field, applied to a list.
    ///
    ///   text      contains   value = what to look for (case-insensitive)
    ///   dropdown  eq         value = the option KEY
    ///   number    gte / lte  value = invariant decimal  "1250.5"
    ///   date      gte / lte  value = ISO date           "2027-03-01"
    ///   checkbox  is         value = "true" | "false"
    ///
    /// Several filters are ANDed. Sent to the API as repeated
    /// ?cf=&lt;id&gt;~&lt;op&gt;~&lt;value&gt; — see CustomFieldFilterCodec.
    /// </summary>
    public class CustomFieldFilter
    {
        public Guid FieldId { get; set; }
        public string Op { get; set; } = string.Empty;
        public string Value { get; set; } = string.Empty;
    }

    public class ReorderCustomFieldsDto
    {
        public string EntityType { get; set; } = string.Empty;
        public List<Guid> OrderedIds { get; set; } = new();
    }
}
