// =====================================================================
// FILE: MerkaiTrial.Application/Services/Pdf/InvoicePdfService.cs
// PACKAGE: QuestPDF (install: dotnet add package QuestPDF)
// PURPOSE: Generate professional PDF invoices with tenant branding
//
// SETUP: In Program.cs add:
//   QuestPDF.Settings.License = LicenseType.Community;  // free for < $1M revenue
//   builder.Services.AddScoped<IInvoicePdfService, InvoicePdfService>();
//
// COMPLETE FILE — 067. THE LINE TABLE GAINS A TAX CLASSIFICATION COLUMN,
// and on an Indian invoice that is not a nicety: a GST invoice has to
// carry the HSN or SAC code against every line. Products have carried the
// code since 051 and it stopped at the product — the line it ended up on
// had no field for it, so the document that legally needs it could not
// print it.
//
// The column appears ONLY when at least one printed line on the invoice
// has a code. Three of Merkai's four markets ask for nothing here, and a
// permanently empty column on a document a customer files with their
// accountant reads as something the sender forgot to fill in.
//
// 055. THE LINE TABLE HAD NO DISCOUNT COLUMN AT ALL.
//
// The totals block showed a "Discount:" line for the whole invoice, so the
// money added up — but a customer looking at a line could not see that it
// had been discounted, or by how much. The quote they accepted showed it
// per line; the invoice that followed did not. There is a Discount column
// now, printing the PERCENTAGE when the line was agreed as one, and the
// Description column gives up the width for it.
//
// 052b. Five changes, the last two found while here.
//
// 1. QUANTITY. Was line.Quantity.ToString(). Quantity is DECIMAL(18,4)
//    since 052, so that prints "3.0000" on a tax invoice. It is
//    QuantityDisplay now — "3", "12.5 m²", "3.5 days".
//
// 2. The Qty column was a CONSTANT 36pt, sized for "12". "12.5 m²" does
//    not fit. Widened to 64pt, taken from the Description column.
//
// 3. THE TAX COLUMN WAS ROUNDING THE RATE. "N0" on (TaxRate * 100)
// 071. A MILESTONE BANNER above the line-items table, printed ONLY on an
// invoice that bills one stage of a quote's payment schedule: "Milestone
// 2 of 3 — On delivery (40%)", with "Amounts shown are 40% of accepted
// quote QUO-0042" under it.
//
// It is not decoration. A milestone invoice's unit prices are a SHARE of
// the quote's, so a customer comparing "1 × 13,500" with a quoted 45,000
// has every reason to query it — and the answer has to be on the same
// page as the figures, not on a screen they cannot see. Every field is a
// snapshot taken when the invoice was raised; the schedule is never
// re-read for a document.
//
//    printed 12.5% as "13%" — on a TAX INVOICE, next to a tax amount
//    calculated from the real 12.5%, so the document contradicts itself
//    in front of whoever files it. "0.##" now, and formatted with the
//    tenant's culture like every other number here.
//
// 4. THE FOOTER SAID "Generated by LeadFlow CRM". On every invoice this
//    workspace has ever sent a customer. QuotePdfService already said
//    "Merkai CRM"; this one had been missed.
//
// 5. Payment amounts used "{p.Amount:N2}", which formats with whatever
//    culture the server thread has rather than the tenant's — so on an
//    INR invoice the totals grouped as 1,00,000.00 and the payment rows
//    beside them as 100,000.00. They use `culture` like everything else
//    now.
// =====================================================================

using MerkaiTrial.Application.Configuration;   // 067: TaxCodes
using MerkaiTrial.Application.DTOs;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.Collections.Generic;              // 067
using System.Globalization;
using System.Linq;                             // 067

namespace MerkaiTrial.Application.Services.Pdf
{
    public interface IInvoicePdfService
    {
        /// <summary>Generate PDF bytes for an invoice. Stream to client or save to disk.</summary>
        byte[] Generate(InvoicePdfModel model);
    }

    // ── Model passed from handler to PDF service ──────────────────────
    public class InvoicePdfModel
    {
        public InvoiceDto   Invoice       { get; set; } = null!;
        public TenantPdfInfo Tenant       { get; set; } = null!;
        public string        CurrencySymbol { get; set; } = string.Empty;
        public string        DateFormat    { get; set; } = "dd/MM/yyyy";
        public string        TaxLabel      { get; set; } = "Tax";
        public string        CurrencyCode  { get; set; } = string.Empty;  // ✅ e.g. "PHP", "INR" — used to derive CultureInfo

        /// <summary>052b: initialised. It was a non-nullable string with no
        /// default, which is a CS8618 warning on every construction.</summary>
        public string NumberFormat { get; set; } = "N2";
    }

    /// <summary>
    /// The SELLER's letterhead — who the document is FROM.
    ///
    /// 065: everything below Country is new. Until 064 a workspace had
    /// nowhere to record an address or a tax number, so this carried a
    /// name, a phone number and a country and the PDF letterhead was four
    /// lines deep. A Thai VAT or Indian GST document is expected to carry
    /// the seller's registered number, and could not.
    ///
    /// THE THREE HELPERS AT THE BOTTOM ARE THE POINT. Both PDF services
    /// and the public quote page lay this block out, and if each one
    /// decided for itself when to print a comma, the three would drift —
    /// which is how "LeadFlow CRM" survived in one footer and not the
    /// other. The rule for assembling an address lives here, once.
    /// </summary>
    public class TenantPdfInfo
    {
        public string Name    { get; set; } = string.Empty;
        public string? Phone  { get; set; }
        public string? Email  { get; set; }
        public string Country { get; set; } = string.Empty;

        // ── 064 company profile ───────────────────────────────────────

        /// <summary>The registered entity, when it differs from Name.</summary>
        public string? LegalName    { get; set; }

        public string? AddressLine1 { get; set; }
        public string? AddressLine2 { get; set; }
        public string? City         { get; set; }
        public string? State        { get; set; }
        public string? PostalCode   { get; set; }
        public string? Website      { get; set; }

        /// <summary>The seller's tax registration number.</summary>
        public string? TaxNumber    { get; set; }

        /// <summary>What that country calls it — "GSTIN", "VAT No.", "TRN".</summary>
        public string? TaxNumberLabel { get; set; }

        // ── Layout rules, in one place ────────────────────────────────

        /// <summary>
        /// The name on the letterhead: the registered entity when there is
        /// one, otherwise what the workspace is called in the app.
        /// </summary>
        public string DisplayName =>
            string.IsNullOrWhiteSpace(LegalName) ? Name : LegalName!;

        /// <summary>
        /// The address, one printable line per element, already stripped of
        /// the parts that are not filled in. Country is always last and
        /// always present; everything above it may be absent.
        ///
        /// Returned as lines rather than one comma-joined string because a
        /// letterhead reads as a block, and because QuestPDF wants one
        /// Text item per line anyway.
        /// </summary>
        public IReadOnlyList<string> AddressLines()
        {
            var lines = new List<string>();

            if (!string.IsNullOrWhiteSpace(AddressLine1)) lines.Add(AddressLine1!.Trim());
            if (!string.IsNullOrWhiteSpace(AddressLine2)) lines.Add(AddressLine2!.Trim());

            // City, State and PostalCode share a line — three separate
            // lines for "Bangkok", "Bangkok", "10120" is a tall thin
            // letterhead that says very little.
            var town = string.Join(" ", new[] { City, State, PostalCode }
                .Where(s => !string.IsNullOrWhiteSpace(s))
                .Select(s => s!.Trim()));

            if (town.Length > 0) lines.Add(town);

            if (!string.IsNullOrWhiteSpace(Country)) lines.Add(Country.Trim());

            return lines;
        }

        /// <summary>
        /// "+66 2 123 4567 · sales@example.com · example.com", or null when
        /// none of the three is filled in.
        /// </summary>
        public string? ContactLine()
        {
            var parts = new[] { Phone, Email, Website }
                .Where(s => !string.IsNullOrWhiteSpace(s))
                .Select(s => s!.Trim())
                .ToArray();

            return parts.Length == 0 ? null : string.Join("  ·  ", parts);
        }

        /// <summary>
        /// "VAT No.: 0105558012345", or null when there is no number.
        ///
        /// A number with no label would print bare, so the label falls back
        /// to a generic word rather than leaving the reader to guess what
        /// the digits are. 064's save path applies the same fallback, so in
        /// practice this one rarely fires.
        /// </summary>
        public string? TaxLine()
        {
            if (string.IsNullOrWhiteSpace(TaxNumber)) return null;

            var label = string.IsNullOrWhiteSpace(TaxNumberLabel)
                ? "Tax No."
                : TaxNumberLabel!.Trim();

            return $"{label}: {TaxNumber!.Trim()}";
        }
    }

    // ── QuestPDF implementation ───────────────────────────────────────
    public class InvoicePdfService : IInvoicePdfService
    {
        // ✅ Map currency code → CultureInfo for number formatting
        // Countries.NumberFormat stores "#,##0.00" patterns (Excel-style), not culture names
        // We derive culture from currency code instead
        // ── 069 ──────────────────────────────────────────────────────
        //
        // FOUR CURRENCIES WERE MISSING. CurrencyConfiguration offers
        // eleven; this switch knew seven, and SGD, MYR, AUD and CAD fell
        // to InvariantCulture — which groups as 1,234.56 rather than
        // wrongly, so nothing looked broken. It simply ignored the
        // reader's locale on a document going to a customer.
        //
        // It mattered more from 069 on. A quote's currency comes from its
        // DEAL, and a product can now be priced in any of the eleven, so
        // a quote in SGD is reachable in a way it was not before.
        //
        // Case-insensitive now, for the same reason the lookups in
        // CurrencyConfiguration became case-insensitive this round: the
        // code arrives from Quotes.Currency, an nvarchar an import can
        // put anything into, rather than from seeded reference data.
        // "inr" used to fall through to InvariantCulture silently.
        private static CultureInfo GetCultureForCurrency(string? currencyCode) =>
            (currencyCode ?? string.Empty).Trim().ToUpperInvariant() switch
        {
            "INR" => new CultureInfo("en-IN"),
            "PHP" => new CultureInfo("en-PH"),
            "THB" => new CultureInfo("th-TH"),
            "AED" => new CultureInfo("en-AE"),
            "USD" => new CultureInfo("en-US"),
            "EUR" => new CultureInfo("en-IE"),
            "GBP" => new CultureInfo("en-GB"),
            "SGD" => new CultureInfo("en-SG"),   // 069
            "MYR" => new CultureInfo("ms-MY"),   // 069
            "AUD" => new CultureInfo("en-AU"),   // 069
            "CAD" => new CultureInfo("en-CA"),   // 069
            _     => CultureInfo.InvariantCulture
        };

        // Brand colours
        private static readonly string AccentHex   = "#4F46E5"; // indigo-600
        private static readonly string LightHex    = "#EEF2FF"; // indigo-50
        private static readonly string MutedHex    = "#6B7280"; // gray-500
        private static readonly string BorderHex   = "#E5E7EB"; // gray-200
        private static readonly string DangerHex   = "#DC2626"; // red-600

        public byte[] Generate(InvoicePdfModel model)
        {
            // ✅ Resolve culture once — never use model.NumberFormat directly
            var culture = GetCultureForCurrency(model.CurrencyCode);

            // ── 067: the tax-classification column ────────────────────
            //
            // The lines are filtered and hoisted out of the table builder
            // for one reason: the column DEFINITION has to know whether
            // the column exists before any row is drawn, and that answer
            // has to come from the same set of lines the rows come from.
            // Deciding it from model.Invoice.Lines while the rows came
            // from the filtered list would, for a credit line carrying the
            // only code on the invoice, add a column of nothing but dashes.
            //
            // Rendered only when at least one PRINTED line has a code, so
            // a Thai or Philippine invoice is byte-for-byte what it was
            // before this round. The header comes from the currency —
            // "HSN / SAC" in India, "Tax code" elsewhere — and TaxCodes is
            // the one place that mapping lives.
            var lineItems = (model.Invoice.Lines ?? new List<InvoiceLineDto>())
                .Where(l => l.LineGrandTotal >= 0)
                .ToList();

            var showTaxCode = TaxCodes.AnyPresent(lineItems.Select(l => l.TaxCode));
            var taxCodeHead = TaxCodes.ColumnHeaderFor(model.CurrencyCode);

            return Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(40);
                    page.DefaultTextStyle(x => x.FontSize(10).FontFamily("Arial"));

                    page.Content().Column(col =>
                    {
                        // ── HEADER ─────────────────────────────────────────────
                        col.Item().Row(row =>
                        {
                            // Left: the SELLER's letterhead.
                            //
                            // 065: was name, email, phone, country — four
                            // lines with no address and no tax number, so
                            // this invoice could not be the tax document
                            // it claims to be in India or Thailand. The
                            // layout rules live on TenantPdfInfo so this
                            // block and QuotePdfService's cannot drift.
                            row.RelativeItem().Column(c =>
                            {
                                c.Item()
                                    .Text(model.Tenant.DisplayName)
                                    .FontSize(20).Bold()
                                    .FontColor(AccentHex);

                                foreach (var line in model.Tenant.AddressLines())
                                    c.Item().Text(line).FontSize(9).FontColor(MutedHex);

                                var contact = model.Tenant.ContactLine();
                                if (contact is not null)
                                    c.Item().PaddingTop(2)
                                        .Text(contact).FontSize(9).FontColor(MutedHex);

                                // Darker and spaced off the rest: on a tax
                                // invoice this is the line somebody is
                                // actually looking for.
                                var tax = model.Tenant.TaxLine();
                                if (tax is not null)
                                    c.Item().PaddingTop(3)
                                        .Text(tax).FontSize(9).Bold().FontColor("#374151");
                            });

                            // Right: INVOICE label + number
                            row.ConstantItem(200).Column(c =>
                            {
                                c.Item().AlignRight()
                                    .Text("INVOICE")
                                    .FontSize(26).Bold()
                                    .FontColor(AccentHex);

                                c.Item().AlignRight()
                                    .Text(model.Invoice.Number)
                                    .FontSize(13).Bold();

                                // Status badge
                                var statusColor = model.Invoice.Status switch
                                {
                                    "Paid"          => "#16A34A",
                                    "PartiallyPaid" => "#D97706",
                                    "Overdue"       => DangerHex,
                                    "Cancelled"     => "#6B7280",
                                    _               => AccentHex
                                };
                                var statusLabel = model.Invoice.Status switch
                                {
                                    "PartiallyPaid" => "PARTIALLY PAID",
                                    _               => model.Invoice.Status.ToUpperInvariant()
                                };

                                c.Item().AlignRight().PaddingTop(4)
                                    .Background(statusColor)
                                    .PaddingHorizontal(8).PaddingVertical(3)
                                    .Text(statusLabel)
                                    .FontSize(8).Bold().FontColor("#FFFFFF");
                            });
                        });

                        col.Item().PaddingVertical(12)
                            .LineHorizontal(1.5f).LineColor(AccentHex);

                        // ── BILL TO + DATES ────────────────────────────────────
                        col.Item().Row(row =>
                        {
                            // Bill To
                            row.RelativeItem().Column(c =>
                            {
                                c.Item().Text("BILL TO")
                                    .FontSize(8).Bold().FontColor(MutedHex);

                                c.Item().PaddingTop(4)
                                    .Text(model.Invoice.CompanyName ?? model.Invoice.ContactName ?? "—")
                                    .Bold().FontSize(11);

                                if (!string.IsNullOrEmpty(model.Invoice.ContactName) &&
                                    model.Invoice.ContactName != model.Invoice.CompanyName)
                                    c.Item().Text(model.Invoice.ContactName)
                                        .FontSize(9).FontColor(MutedHex);

                                if (!string.IsNullOrEmpty(model.Invoice.DealTitle))
                                    c.Item().PaddingTop(2)
                                        .Text($"Re: {model.Invoice.DealTitle}")
                                        .FontSize(9).Italic().FontColor(MutedHex);
                            });

                            // Dates
                            row.ConstantItem(220).Column(c =>
                            {
                                void DateRow(string label, string value, bool overdue = false)
                                {
                                    c.Item().Row(r =>
                                    {
                                        r.RelativeItem()
                                            .Text(label).FontSize(9).FontColor(MutedHex);
                                        var t = r.ConstantItem(120).AlignRight()
                                            .Text(value).FontSize(9)
                                            .FontColor(overdue ? DangerHex : "#000000");
                                        if (overdue) t.Bold();
                                    });
                                    c.Item().PaddingBottom(3);
                                }

                                DateRow("Issue date:",
                                    model.Invoice.IssueDateUtc.ToString(
                                        model.DateFormat, CultureInfo.InvariantCulture));

                                if (model.Invoice.DueDateUtc.HasValue)
                                {
                                    var overdue = model.Invoice.IsOverdue;
                                    DateRow($"Due date{(overdue ? " ⚠" : "")}:",
                                        model.Invoice.DueDateUtc.Value.ToString(
                                            model.DateFormat, CultureInfo.InvariantCulture),
                                        overdue);
                                }

                                if (!string.IsNullOrEmpty(model.Invoice.QuoteNumber))
                                    DateRow("Quote ref:", model.Invoice.QuoteNumber);
                            });
                        });

                        // ── MILESTONE BANNER (071) ─────────────────────────────
                        //
                        // Printed ONLY on an invoice that bills ONE STAGE
                        // of a quote's payment schedule. An ordinary
                        // invoice — manual, or for a whole quote — prints
                        // nothing here and renders exactly as it did
                        // before this round.
                        //
                        // WHY IT HAS TO BE ON THE DOCUMENT, not just on
                        // the screen: a milestone invoice's unit prices
                        // are a SHARE of the quote's. A customer's
                        // accounts department reading "1 × 13,500"
                        // against a quoted 45,000 has every reason to
                        // query it, and the answer belongs on the same
                        // page as the figures.
                        //
                        // Everything here is a SNAPSHOT taken when the
                        // invoice was raised. The schedule is never
                        // re-read for a document: renaming a stage must
                        // not rewrite an invoice that is already filed in
                        // somebody's tax return.
                        if (model.Invoice.IsMilestoneInvoice)
                        {
                            col.Item().PaddingTop(16)
                                .Background(LightHex)
                                .Padding(9)
                                .Column(c =>
                                {
                                    c.Item().Text(model.Invoice.MilestoneLabel ?? "Milestone")
                                        .FontSize(10).Bold().FontColor(AccentHex);

                                    if (!string.IsNullOrWhiteSpace(model.Invoice.MilestoneBasisNote))
                                    {
                                        c.Item().PaddingTop(3)
                                            .Text(model.Invoice.MilestoneBasisNote)
                                            .FontSize(8.5f).FontColor(MutedHex);
                                    }

                                    c.Item().PaddingTop(2)
                                        .Text("Every line of the accepted quote appears below at this stage's share, " +
                                              "keeping its own tax rate and tax classification.")
                                        .FontSize(8).FontColor(MutedHex);
                                });
                        }

                        col.Item().PaddingTop(20);

                        // ── LINE ITEMS TABLE ───────────────────────────────────
                        col.Item().Table(table =>
                        {
                            // Column definitions
                            table.ColumnsDefinition(cols =>
                            {
                                cols.ConstantColumn(24);  // #
                                cols.RelativeColumn(3);   // Item
                                // 052b: Description 4 -> 3.3, Qty 36pt -> 64pt.
                                // A quantity is "12.5 m²" now, not "12".
                                // 055: Description 3.3 -> 2.2 to make room for
                                // Discount, which this table never had.
                                // 067: Description 2.2 -> 1.4 when there are
                                // codes to print. Taken from Description for
                                // the same reason 055 took from it: it is the
                                // only column here that WRAPS, so it loses
                                // height rather than content, while every
                                // other column is a fixed-width number that
                                // would start clipping.
                                cols.RelativeColumn(showTaxCode ? 1.4f : 2.2f);// Description
                                if (showTaxCode)
                                    cols.ConstantColumn(66);  // 067: HSN / SAC
                                cols.ConstantColumn(64);  // Qty
                                cols.ConstantColumn(80);  // Unit Price
                                cols.ConstantColumn(72);  // Discount   (055)
                                cols.ConstantColumn(44);  // Tax %
                                cols.ConstantColumn(80);  // Total
                            });

                            // Header row
                            void HeaderCell(string text, bool alignRight = false)
                            {
                                table.Cell()
                                    .Background(AccentHex)
                                    .PaddingHorizontal(6).PaddingVertical(5)
                                    .Element(e => alignRight ? e.AlignRight() : e)
                                    .Text(text)
                                    .FontSize(8.5f).Bold().FontColor("#FFFFFF");
                            }

                            HeaderCell("#");
                            HeaderCell("Item");
                            HeaderCell("Description");
                            if (showTaxCode) HeaderCell(taxCodeHead);   // 067
                            HeaderCell("Qty", true);
                            HeaderCell("Unit Price", true);
                            HeaderCell("Discount", true);          // 055
                            HeaderCell($"{model.TaxLabel} %", true);
                            HeaderCell("Total", true);

                            // Data rows — lineItems is built at the top of
                            // Generate, so the column definition above and
                            // these rows cannot disagree about which lines
                            // the invoice has. (067)
                            for (int i = 0; i < lineItems.Count; i++)
                            {
                                var line   = lineItems[i];
                                var rowBg  = i % 2 == 0 ? "#FFFFFF" : LightHex;

                                void DataCell(string text, bool alignRight = false,
                                              bool bold = false, string? color = null)
                                {
                                    var t = table.Cell()
                                        .Background(rowBg)
                                        .BorderBottom(0.5f).BorderColor(BorderHex)
                                        .PaddingHorizontal(6).PaddingVertical(5)
                                        .Element(e => alignRight ? e.AlignRight() : e)
                                        .Text(text)
                                        .FontSize(9)
                                        .FontColor(color ?? "#000000");
                                    if (bold) t.Bold();
                                }

                                var sym = model.CurrencySymbol;

                                DataCell((i + 1).ToString(), color: MutedHex);
                                DataCell(line.Name ?? "—", bold: true);
                                DataCell(line.Description ?? "—", color: MutedHex);

                                // 067. An em dash where a line has no code,
                                // so a reader can tell "not classified" from
                                // "the column didn't print". Left-aligned: a
                                // code is a reference, not a number.
                                if (showTaxCode)
                                    DataCell(line.HasTaxCode ? line.TaxCode! : "—",
                                        color: line.HasTaxCode ? "#374151" : MutedHex);

                                // 052b: "12.5 m²", not "12.5000".
                                DataCell(line.QuantityDisplay, alignRight: true);
                                DataCell($"{sym}{line.UnitPrice.ToString("N2", culture)}", alignRight: true);

                                // 055. The percentage when the line was agreed as
                                // one, with what it came to underneath.
                                var discText = line.LineDiscount <= 0
                                    ? "—"
                                    : line.DiscountLabel is not null
                                        ? $"{line.DiscountLabel}\n{sym}{line.LineDiscount.ToString("N2", culture)}"
                                        : $"-{sym}{line.LineDiscount.ToString("N2", culture)}";

                                DataCell(discText, alignRight: true,
                                    color: line.LineDiscount > 0 ? "#16A34A" : MutedHex);

                                // 052b: "0.##" not "N0" — N0 printed 12.5% as "13%"
                                // beside a tax amount worked out from 12.5%.
                                DataCell($"{(line.TaxRate * 100).ToString("0.##", culture)}%",
                                    alignRight: true, color: MutedHex);
                                DataCell($"{sym}{line.LineGrandTotal.ToString("N2", culture)}", alignRight: true, bold: true);
                            }
                        });

                        // ── TOTALS ─────────────────────────────────────────────
                        col.Item().PaddingTop(12).Row(row =>
                        {
                            row.RelativeItem(); // spacer

                            row.ConstantItem(240).Column(totals =>
                            {
                                var sym = model.CurrencySymbol;

                                void TotalRow(string label, decimal amount,
                                              bool bold = false, string? color = null,
                                              bool separator = false)
                                {
                                    if (separator)
                                        totals.Item()
                                            .LineHorizontal(0.5f).LineColor(BorderHex);

                                    totals.Item().PaddingVertical(2).Row(r =>
                                    {
                                        var lbl = r.RelativeItem()
                                            .Text(label)
                                            .FontSize(9).FontColor(color ?? MutedHex);
                                        if (bold) lbl.Bold();
                                        var amt = r.ConstantItem(100).AlignRight()
                                            .Text($"{sym}{amount.ToString("N2", culture)}")
                                            .FontSize(9).FontColor(color ?? "#000000");
                                        if (bold) amt.Bold();
                                    });
                                }

                                TotalRow("Subtotal:", model.Invoice.Subtotal);

                                if (model.Invoice.DiscountTotal > 0)
                                    TotalRow("Discount:", -model.Invoice.DiscountTotal,
                                             color: "#16A34A");

                                TotalRow($"{model.TaxLabel}:", model.Invoice.TaxTotal);

                                totals.Item().PaddingVertical(4)
                                    .LineHorizontal(1.5f).LineColor(AccentHex);

                                totals.Item().PaddingVertical(3).Row(r =>
                                {
                                    r.RelativeItem()
                                        .Text("Grand Total:")
                                        .FontSize(12).Bold().FontColor(AccentHex);
                                    r.ConstantItem(100).AlignRight()
                                        .Text($"{sym}{model.Invoice.GrandTotal.ToString("N2", culture)}")
                                        .FontSize(13).Bold().FontColor(AccentHex);
                                });

                                if (model.Invoice.TotalPaid > 0)
                                {
                                    TotalRow("Paid:", model.Invoice.TotalPaid, color: "#16A34A");
                                    totals.Item().PaddingVertical(3).Row(r =>
                                    {
                                        r.RelativeItem()
                                            .Text("Balance Due:")
                                            .FontSize(11).Bold()
                                            .FontColor(model.Invoice.Balance > 0 ? DangerHex : "#16A34A");
                                        r.ConstantItem(100).AlignRight()
                                            .Text($"{sym}{model.Invoice.Balance.ToString("N2", culture)}")
                                            .FontSize(12).Bold()
                                            .FontColor(model.Invoice.Balance > 0 ? DangerHex : "#16A34A");
                                    });
                                }
                            });
                        });

                        // ── PAYMENT HISTORY ────────────────────────────────────
                        if (model.Invoice.Payments.Any())
                        {
                            col.Item().PaddingTop(20);
                            col.Item().Text("Payment History")
                                .FontSize(10).Bold().FontColor(AccentHex);
                            col.Item().PaddingTop(4);

                            col.Item().Table(table =>
                            {
                                table.ColumnsDefinition(cols =>
                                {
                                    cols.RelativeColumn(2);
                                    cols.RelativeColumn(2);
                                    cols.RelativeColumn(3);
                                    cols.RelativeColumn(2);
                                });

                                void PH(string text)
                                    => table.Cell()
                                        .Background(LightHex)
                                        .PaddingHorizontal(6).PaddingVertical(4)
                                        .Text(text).FontSize(8.5f).Bold().FontColor(MutedHex);

                                PH("Date"); PH("Method"); PH("Reference"); PH("Amount");

                                foreach (var p in model.Invoice.Payments)
                                {
                                    void PD(string text, bool right = false)
                                        => table.Cell()
                                            .BorderBottom(0.5f).BorderColor(BorderHex)
                                            .PaddingHorizontal(6).PaddingVertical(4)
                                            .Element(e => right ? e.AlignRight() : e)
                                            .Text(text).FontSize(9);

                                    PD(p.PaidAtUtc.ToString(model.DateFormat, CultureInfo.InvariantCulture));
                                    PD(p.Method);
                                    PD(p.ProviderTxnId ?? p.Notes ?? "—");
                                    // 052b: `culture`, so a payment row groups the
                                    // same way as the totals a few inches above it.
                                    PD($"{model.CurrencySymbol}{p.Amount.ToString("N2", culture)}", right: true);
                                }
                            });
                        }

                        // ── NOTES ──────────────────────────────────────────────
                        if (!string.IsNullOrWhiteSpace(model.Invoice.Notes))
                        {
                            col.Item().PaddingTop(20)
                                .Background(LightHex)
                                .Padding(10)
                                .Column(c =>
                                {
                                    c.Item().Text("Notes")
                                        .FontSize(9).Bold().FontColor(AccentHex);
                                    c.Item().PaddingTop(4)
                                        .Text(model.Invoice.Notes)
                                        .FontSize(9).FontColor(MutedHex);
                                });
                        }
                    });

                    // ── FOOTER ─────────────────────────────────────────────────
                    page.Footer().Row(row =>
                    {
                        row.RelativeItem()
                            .Text(x =>
                            {
                                // 052b: was "LeadFlow CRM" — the old working name,
                                // on every invoice sent to a customer.
                                x.Span("Generated by Merkai CRM  ·  ")
                                    .FontSize(8).FontColor(MutedHex);
                                x.Span(DateTime.UtcNow.ToString("dd/MM/yyyy HH:mm"))
                                    .FontSize(8).FontColor(MutedHex);
                            });
                        row.ConstantItem(60).AlignRight()
                            .Text(x =>
                            {
                                x.Span("Page ").FontSize(8).FontColor(MutedHex);
                                x.CurrentPageNumber().FontSize(8).FontColor(MutedHex);
                                x.Span(" of ").FontSize(8).FontColor(MutedHex);
                                x.TotalPages().FontSize(8).FontColor(MutedHex);
                            });
                    });
                });
            }).GeneratePdf();
        }
    }
}
